### ISSUE TITLE
Na určité obrázky nefunguje

### ISSUE THREAD

**Issue by stralkaj** [baraja-core/image-generator#13]
Nevím proč, ale asi na 20% všech obrázků JPEG mi ImageGenerator nefunguje. Příklady:

- https://www.promokupon.cz/img/company/785/logo.jpg existuje, ale https://www.promokupon.cz/img/company/785/logo__w160h160_f267d3.jpg nefunguje

Podpobně je to např. u:
- https://www.promokupon.cz/img/company/871/logo.jpg
- https://www.promokupon.cz/img/company/878/logo.jpg
- https://www.promokupon.cz/img/company/849/logo.jpg

Je nějaký společný jmenovatel u těchto obrázků, se kterým může být problém?

**Comment by stralkaj** [comment]
Jinak logují se někde obrázky, které se nepodařilo nalézt a vygeneruje se dummy image?

**Comment by janbarasek** [comment]
Closed in https://github.com/baraja-core/image-generator/commit/87e03bf8e88048d1db033a5b41aeed5ad8939043
